Repository gsk-aiops/bellman, pull requests merged in 2021-09, with the labels that each got.

#531 introduce Relational typeclass and typed dataframes
  build.sbt
  modules/engine/src/main/scala/com/gsk/kg/engine/Compiler.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/Multiset.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/PropertyExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/Analyzer.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncAgg.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/PathFrame.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/package.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/relational/relational.scala
  modules/engine/src/main/scala/higherkindness/droste/contrib/NewTypesSyntax.scala
  modules/engine/src/test/scala-2.11/com/gsk/kg/engine/DataFrameGeneratorSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/MultisetSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/properties/FuncPropertySpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/relational/relationalLaws.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/scalacheck/DataFrameImplicits.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/scalacheck/all.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/utils/MultisetMatchers.scala
Labels: enhancement

#533 Typed dataframes: add DataFrame typer
  build.sbt
  modules/engine/src/main/scala/com/gsk/kg/engine/Compiler.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/DataFrameTyper.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/RdfFormatter.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/DataFrameTyperTest.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/RdfFormatterSpec.scala
  modules/parser/src/main/resources/application.conf
  modules/parser/src/main/scala/com/gsk/kg/config/Config.scala
  modules/parser/src/test/scala/com/gsk/kg/sparqlparser/TestConfig.scala
Labels: enhancement

#537 Update kind-projector to 0.13.2
  build.sbt
Labels: dependency-update

#538 Update RDF Tests report
  rdf-test-results.md
Labels: documentation

#540 Property path reverse final
  modules/engine/src/main/scala/com/gsk/kg/engine/DAG.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/PropertyExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/GraphsPushdown.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/Optimizer.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/PropertyPathRewrite.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/SubqueryPushdown.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/optimizer/PropertyPathRewriteSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/properties/FuncPropertySpec.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expr.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/PropertyExpression.scala
  modules/parser/src/test/scala/com/gsk/kg/sparqlparser/ExprParserSpec.scala
  modules/site/src/main/scala/com/gsk/kg/site/contrib/reftree/prelude.scala
Labels: enhancement

#542 type Funcforms and Literals
  modules/engine/src/main/scala/com/gsk/kg/engine/DataFrameTyper.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/syntax/package.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/typed/functions/Promotion.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/typed/functions/TypedFuncForms.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/typed/functions/TypedLiterals.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/typed/functions/TypedFuncFormsSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/typed/functions/TypedLiteralsSpec.scala
Labels: enhancement

#546 fixed bug where graph variables was being set to null on union operation
  modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/Multiset.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/relational/relational.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/GraphSpec.scala
Labels: bug

#549 added support for default and named graphs to property paths
  modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/PathFrame.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/GraphsPushdown.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/properties/FuncPropertySpec.scala
Labels: enhancement

#557 Update sbt-scoverage to 1.9.0
  project/plugins.sbt
Labels: dependency-update

#561 Update sbt-ci-release to 1.5.9
  project/plugins.sbt
Labels: dependency-update

#564 Feature/typed dataframes funcstrings
  modules/engine/src/main/scala/com/gsk/kg/engine/RdfFormatter.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/syntax/package.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/typed/functions/FuncStrings.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/typed/functions/FuncStringsSpec.scala
Labels: enhancement

#565 Feature/typed funcagg
  modules/engine/src/main/scala/com/gsk/kg/engine/typed/functions/FuncAgg.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/typed/functions/FuncAggSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/typed/functions/FuncStringsSpec.scala
Labels: enhancement

#566 Add complex property path test
  modules/engine/src/main/scala/com/gsk/kg/engine/PropertyExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/PathFrame.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/PropertyPathRewrite.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/relational/relational.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/properties/FuncPropertySpec.scala
Labels: bug, enhancement

#568 Feature/typed funcdates
  modules/engine/src/main/scala/com/gsk/kg/engine/syntax/package.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/typed/functions/FuncDates.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/typed/functions/FuncDatesSpec.scala
Labels: enhancement

#569 Feature/typed funchash
  modules/engine/src/main/scala/com/gsk/kg/engine/typed/functions/FuncHash.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/typed/functions/FuncHashSpec.scala
Labels: enhancement
