Repository gsk-aiops/bellman, pull requests merged in 2021-10, with the labels that each got.

#571 first version of FuncNumerics
  modules/engine/src/main/scala/com/gsk/kg/engine/typed/functions/FuncNumerics.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/typed/functions/FuncNumericsSpec.scala
Labels: enhancement

#574 Update RDF Tests report
  rdf-test-results.md
Labels: documentation

#572 Feature/typed functerms
  modules/engine/src/main/scala/com/gsk/kg/engine/typed/functions/FuncTerms.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/typed/functions/FuncTermsSpec.scala
Labels: enhancement

#576 fixed property expression when configured in inclusive mode
  modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/PropertyExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/PathFrame.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/properties/FuncPropertySpec.scala
Labels: bug

#581 add more tests from Having to check bug AIPL-4536. It solve with the …
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/HavingSpec.scala
Labels: bug
