Repository gsk-aiops/bellman, pull requests merged in 2021-06, with the labels that each got.

#429 Describe query
  .gitignore
  modules/engine/src/main/scala/com/gsk/kg/engine/DAG.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/Multiset.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/DescribeSpec.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expr.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/QueryConstruct.scala
Labels: enhancement

#433 reimplement queryextractor using Jena's sse
  modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/QueryExtractorSpec.scala
Labels: bug

#435 Add UUID function
  modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncTerms.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/UUIDSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncTermsSpec.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
  modules/parser/src/test/scala/com/gsk/kg/sparqlparser/BuiltInFuncParserSpec.scala
Labels: enhancement

#438 Update sbt to 1.5.4
  project/build.properties
Labels: dependency-update

#427 Add support arithmetic funcs
  modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncArithmetics.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/ArithmeticSpec.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ArithmeticParser.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ExprParser.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ExpressionParser.scala
  modules/parser/src/test/scala/com/gsk/kg/sparqlparser/ArithmeticParserSpec.scala
  scalastyle-config.xml
Labels: enhancement

#441 Add support for numeric types
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncNumerics.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/Ceilspec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncNumericsSpec.scala
Labels: bug

#443 added type promotion to arithmetic operations
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncAgg.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncArithmetics.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncForms.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncNumerics.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/Literals.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/Ceilspec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncArithmeticSpec.scala
Labels: enhancement

#445 fixed equals on plain string literals
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/Literals.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/EqualsSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncFormsSpec.scala
Labels: bug

#444 Add round function
  modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncNumerics.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/RoundSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncNumericsSpec.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
  modules/parser/src/test/scala/com/gsk/kg/sparqlparser/BuiltInFuncParserSpec.scala
Labels: enhancement

#446 Reorder BGPs optimization
  build.sbt
  modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/Optimizer.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/ReorderBgps.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/optimizer/ReorderBgpsSpec.scala
  modules/parser/src/main/scala/com/gsk/kg/sparql/syntax/Interpolators.scala
Labels: enhancement

#448 make rdf-tests rely on test artifacts
  .github/workflows/rdf-tests.yml
  build.sbt
Labels: bug

#447 Add rand function
  modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncNumerics.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/RandSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncNumericsSpec.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
  modules/parser/src/test/scala/com/gsk/kg/sparqlparser/BuiltInFuncParserSpec.scala
Labels: enhancement

#454 Update RDF Tests report
  rdf-test-results.md
Labels: documentation

#449 Add abs function
  modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncNumerics.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/AbsSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncNumericsSpec.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
  modules/parser/src/test/scala/com/gsk/kg/sparqlparser/BuiltInFuncParserSpec.scala
Labels: enhancement

#455 fix rdf-test to get more accuracy in reports
  modules/rdf-tests/src/test/scala/com/gsk/kg/RdfTests.scala
Labels: bug

#456 Update RDF Tests report
  rdf-test-results.md
Labels: documentation

#452 Add floor function
  modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncNumerics.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/FloorSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncNumericsSpec.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
  modules/parser/src/test/scala/com/gsk/kg/sparqlparser/BuiltInFuncParserSpec.scala
Labels: enhancement

#457 Add strUuid spark implementation
  modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncTerms.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/StrUuidSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncTermsSpec.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
  modules/parser/src/test/scala/com/gsk/kg/sparqlparser/BuiltInFuncParserSpec.scala
Labels: enhancement
