Repository gsk-aiops/bellman, pull requests merged in 2021-07, with the labels that each got.

#463 Path properties algebra
  modules/engine/src/main/scala/com/gsk/kg/engine/DAG.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/GraphsPushdown.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/SubqueryPushdown.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expr.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ExprParser.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/PropertyExpression.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/PropertyPathParser.scala
  modules/parser/src/test/resources/queries/q50-property-simple-alt.sparql
  modules/parser/src/test/resources/queries/q51-property-simple-rev.sparql
  modules/parser/src/test/resources/queries/q52-property-simple-seq.sparql
  modules/parser/src/test/resources/queries/q53-property-simple-plus.sparql
  modules/parser/src/test/resources/queries/q54-property-simple-star.sparql
  modules/parser/src/test/resources/queries/q55-property-simple-question.sparql
  modules/parser/src/test/resources/queries/q56-property-simple-negation.sparql
  modules/parser/src/test/resources/queries/q57-property-simple-nm.sparql
  modules/parser/src/test/resources/queries/q58-property-simple-n.sparql
  modules/parser/src/test/resources/queries/q59-property-simple-ncomma.sparql
  modules/parser/src/test/resources/queries/q60-property-simple-comman.sparql
  modules/parser/src/test/resources/queries/q61-property-complex-1.sparql
  modules/parser/src/test/resources/queries/q62-property-complex-2.sparql
  modules/parser/src/test/scala/com/gsk/kg/sparqlparser/ExprParserSpec.scala
  modules/parser/src/test/scala/com/gsk/kg/sparqlparser/PropertyExpressionParserSpec.scala
  modules/site/src/main/scala/com/gsk/kg/site/contrib/reftree/prelude.scala
Labels: enhancement

#462 Update RDF Tests report
  rdf-test-results.md
Labels: documentation

#465 setup codecov
  .github/workflows/scala.yml
  build.sbt
  project/plugins.sbt
Labels: enhancement

#466 add status badges to readme
  README.md
Labels: documentation

#469 year function impl
  modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncDates.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/Literals.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/YearSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncDatesSpec.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParser.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
  modules/parser/src/test/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParserSpec.scala
Labels: enhancement

#468 constrain the number off shuffle partitions to 1 in test
  .github/workflows/scala.yml
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/Bug3255Spec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/SparkSpec.scala
Labels: enhancement

#471 Add month function
  modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncDates.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/MonthSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncDatesSpec.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParser.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
  modules/parser/src/test/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParserSpec.scala
Labels: enhancement

#470 add support for alternative property path
  modules/engine/src/main/scala/com/gsk/kg/engine/DAG.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/PropertyExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/GraphsPushdown.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/optimizer/SubqueryPushdown.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/EngineError.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expr.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ExprParser.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/PropertyExpression.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/PropertyPathParser.scala
  modules/parser/src/test/scala/com/gsk/kg/sparqlparser/ExprParserSpec.scala
  modules/parser/src/test/scala/com/gsk/kg/sparqlparser/PropertyExpressionParserSpec.scala
  modules/site/src/main/scala/com/gsk/kg/site/contrib/reftree/prelude.scala
Labels: enhancement

#474 use strict non-whitespace combinator to capture whitespace inside
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/StringValParser.scala
  modules/parser/src/test/scala/com/gsk/kg/sparqlparser/StringValParserSpec.scala
Labels: enhancement

#473 add hours function
  modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncDates.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/HoursSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncDatesSpec.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParser.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
  modules/parser/src/test/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParserSpec.scala
Labels: enhancement

#475 Add strlang function
  modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncTerms.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/StrlangSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncTermsSpec.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ExprParser.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/ExpressionParser.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/MathFuncParser.scala
  modules/parser/src/test/scala/com/gsk/kg/sparqlparser/BuiltInFuncParserSpec.scala
  modules/parser/src/test/scala/com/gsk/kg/sparqlparser/MathFuncParserSpec.scala
Labels: enhancement

#479 Update sbt-scalafmt to 2.4.3
  project/plugins.sbt
Labels: dependency-update

#478 added implementation for seq property path
  build.sbt
  modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/PropertyExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/properties/FuncPropertySpec.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/EngineError.scala
Labels: enhancement

#477 seconds function implementation
  modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncDates.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/SecondsSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncDatesSpec.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParser.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
  modules/parser/src/test/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParserSpec.scala
Labels: enhancement

#480 timezone function implementation
  modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncDates.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/TimezoneSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncDatesSpec.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParser.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
  modules/parser/src/test/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParserSpec.scala
Labels: enhancement

#481 Add tz function
  modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncDates.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/TzSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncDatesSpec.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParser.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
  modules/parser/src/test/scala/com/gsk/kg/sparqlparser/DateTimeFuncsParserSpec.scala
Labels: enhancement

#483 Update sbt to 1.5.5
  project/build.properties
Labels: dependency-update

#485 add support one or more property path (+)
  modules/engine/src/main/scala/com/gsk/kg/engine/Engine.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/PropertyExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/package.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/properties/FuncPropertySpec.scala
Labels: enhancement

#487 add support zero or more property path (*)
  modules/engine/src/main/scala/com/gsk/kg/engine/PropertyExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/properties/FuncPropertySpec.scala
Labels: enhancement

#488 Add datatype function
  modules/engine/src/main/scala/com/gsk/kg/engine/ExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/QueryExtractor.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/analyzer/FindUnboundVariables.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/data/ToTree.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/FuncTerms.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/functions/FuncTermsSpec.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/BuiltInFuncParser.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/Expression.scala
  modules/parser/src/test/scala/com/gsk/kg/sparqlparser/BuiltInFuncParserSpec.scala
  modules/rdf-tests/src/test/scala/com/gsk/kg/RdfTests.scala
Labels: enhancement

#499 fixed default graph when dataset explicitly constructed
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/CompilerSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/InclusiveGraphsSpec.scala
  modules/parser/src/main/scala/com/gsk/kg/sparqlparser/QueryConstruct.scala
Labels: bug

#491 add support property path zero or one
  modules/engine/src/main/scala/com/gsk/kg/engine/PropertyExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/properties/FuncPropertySpec.scala
Labels: enhancement

#497 Property path exactly n
  modules/engine/src/main/scala/com/gsk/kg/engine/PropertyExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/PathFrame.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/properties/FuncPropertySpec.scala
Labels: enhancement

#502 Property path between n m
  modules/engine/src/main/scala/com/gsk/kg/engine/PropertyExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/PathFrame.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/properties/FuncPropertySpec.scala
Labels: enhancement

#503 Property paths n or more and zero to n
  modules/engine/src/main/scala/com/gsk/kg/engine/PropertyExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/PathFrame.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/properties/FuncPropertySpec.scala
Labels: enhancement
