Repository gsk-aiops/bellman, pull requests merged in 2021-08, with the labels that each got.

#515 Update sbt-sonatype to 3.9.9
  project/plugins.sbt
Labels: dependency-update

#517 bump spark to 2.4.4 to match hudi version
  build.sbt
Labels: dependencies, dependency-update

#519 Update sbt-scalafix to 0.9.30
  project/plugins.sbt
Labels: dependency-update

#505 added support for not one of property path
  modules/engine/src/main/scala/com/gsk/kg/engine/PropertyExpressionF.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/functions/PathFrame.scala
  modules/engine/src/main/scala/com/gsk/kg/engine/properties/FuncProperty.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/compiler/PropertyPathsSpec.scala
  modules/engine/src/test/scala/com/gsk/kg/engine/properties/FuncPropertySpec.scala
Labels: enhancement

#530 Update sbt-sonatype to 3.9.10
  project/plugins.sbt
Labels: dependency-update
